### GET verifikasi email
POST http://192.168.0.111:3000/api/emailvalidation/
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "email" : "rendratrykusuma@gmail.com",
  "otp" : "8423"
}

### CREATE akun nasabah
POST http://192.168.1.224:3000/api/datanasabah
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
"email" : "rendratrykusuma@gmail.com"
}


### CREATE pengajuan kredit
POST http://localhost:3000/api/pengajuankredit
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "id" : 76,
  "penggunaan" : "Bayar sekolah Anak",
  "pekerjaan" : "PNS",
  "gaji" : "5000000",
  "gaji_tambahan" : "3000000",
  "besar_pengajuan" : 10000000,
  "tenor" : "3 bulan",
  "score" : 100
}

### UPDATE pin nasabah
PUT http://192.168.0.111:3000/api/pinnasabah/62
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
"pin" : "677890"
}

### UPDATE mengurangi saldo nasabah
PUT http://localhost:3000/api/minsaldo/22
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "saldo" : 10000
}


### CREATE PENARIKAN saldo nasabah
POST http://localhost:3000/api/penarikansaldo
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "id" : 76,
  "jml_penarikan" : 100000,
  "bank" : "BRI",
  "norek" : "389993876379",
  "nama_pemilik" : "Pambudi"
}


### GET saldo nasabah
GET http://192.168.162.47:3000/api/getsaldo/70
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

### GET login nasabah
POST http://localhost:3000/api/login
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "email" : "rendratrykusuma@gmail.com",
  "pin" : "111111"
}



### GET nik nasabah
POST http://localhost:3000/api/getnik/
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "nik" : 3519110907000001
}

### UPDATE keamanan nasabah
PUT http://localhost:3000/api/keamanannasabah/76
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "pertanyaan" : "Siapa nama gurumu?",
  "jawaban" : "Subandi"
}


### CHECK keamanan nasabah
POST http://localhost:3000/api/keamanancheck/76
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "pertanyaan" : "Siapa nama gurumu?",
  "jawaban" : "Subandi"
}


### UPDATE datanasabah by id
PUT http://192.168.162.47:3000/api/datanasabah/67
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "nik" : "3519110856210001",
  "nama" : "Rendra",
  "alamat" : "Caruban",
  "no_hp" : "081774888409",
  "lahir" : "2001-24-08",
  "kota" : "Madiun",
  "ktp" : "ktp.jpg",
  "swa" : "swa.jpg"
}

### GET profile
GET http://192.168.66.47:3000/api/profile/71
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

### Upload Ava
PUT http://192.168.66.47:3000/api/ava/71
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "ava" : "ava.jpg"
}

### Email Check
POST http://localhost:3000/api/emailcheck
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "email" : "rendratry1@gmail.com"
}


### Nik Check
POST http://localhost:3000/api/nikcheck
X-API-Key: myfin
Accept: application/json
Content-Type: application/json

{
  "nik" : "3519110907000001"
}

### Get Transaksi
GET http://localhost:3000/api/transaksi/76/pending
X-API-Key: myfin
Accept: application/json
Content-Type: application/json