// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"myfin/app"
	"myfin/controller"
	"myfin/middleware"
	"myfin/repository"
	"myfin/service"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	datanasabahRepositoryImpl := repository.NewDatanasabahRepository()
	db := app.GetConnection()
	validate := validator.New()
	datanasabahServiceImpl := service.NewDatanasabahService(datanasabahRepositoryImpl, db, validate)
	datanasabahControllerImpl := controller.NewDatanasabahController(datanasabahServiceImpl)
	pertanyaanKeamananRepositoryImpl := repository.NewPertanyaanKeamananRepository()
	keamananNasabahServiceImpl := service.NewKeamananNasabahService(pertanyaanKeamananRepositoryImpl, db, validate)
	keamananNasabahControllerImpl := controller.NewKeamananNasabahController(keamananNasabahServiceImpl)
	akunNasabahRepositoryImpl := repository.NewAkunNasabahRepositoryImpl()
	akunNasabahServiceImpl := service.NewAkunNasabahService(akunNasabahRepositoryImpl, db, validate)
	akunNasabahControllerImpl := controller.NewAkunNasabahController(akunNasabahServiceImpl)
	pengajuanKreditRepositoryImpl := repository.NewPengajuanKreditRepository()
	pengajuanKreditServiceImpl := service.NewPengajuanKreditService(pengajuanKreditRepositoryImpl, db, validate)
	pengajuanKreditControllerImpl := controller.NewPengajuanKreditControllerImpl(pengajuanKreditServiceImpl)
	emailValidationRepositoryImpl := repository.NewEmailValidationRepository()
	emailValidationServiceImpl := service.NewEmailValidationService(emailValidationRepositoryImpl, db, validate)
	emailValidationControllerImpl := controller.NewEmailValidationController(emailValidationServiceImpl)
	penarikanSaldoRepositoryImpl := repository.NewPenarikanSaldoRepositoryImpl()
	penarikanSaldoServiceImpl := service.NewPenarikanSaldoServiceImpl(penarikanSaldoRepositoryImpl, db, validate)
	penarikanSaldoControllerImpl := controller.NewPenarikanSaldoControllerImpl(penarikanSaldoServiceImpl)
	getSaldoRepositoryImpl := repository.NewGetSaldoRepository()
	getSaldoServiceImpl := service.NewGetSaldoService(getSaldoRepositoryImpl, db, validate)
	getSaldoControllerImpl := controller.NewGetSaldoController(getSaldoServiceImpl)
	getNikRepositoryImpl := repository.NewGetNikRepository()
	getNikServiceImpl := service.NewGetNikService(getNikRepositoryImpl, db, validate)
	getNikControllerImpl := controller.NewGetNikController(getNikServiceImpl)
	loginNasabahRepositoryImpl := repository.NewLoginNasabahRepository()
	loginNasabahServiceImpl := service.NewLoginNasabahService(loginNasabahRepositoryImpl, db, validate)
	loginNasabahControllerImpl := controller.NewLoginNasabahController(loginNasabahServiceImpl)
	getProfileRepositoryImpl := repository.NewGetProfileRepository()
	getProfileServiceImpl := service.NewGetProfileService(getProfileRepositoryImpl, db, validate)
	getProfileControllerImpl := controller.NewGetProfileController(getProfileServiceImpl)
	avaUploadRepositoryImpl := repository.NewAvaUploadRepository()
	avaUploadServiceImpl := service.NewAvaUploadService(avaUploadRepositoryImpl, db, validate)
	avaUploadControllerImpl := controller.NewAvaUploadController(avaUploadServiceImpl)
	pinNasabahRepositoryImpl := repository.NewPinNasabahRepositoryImpl()
	pinNasabahServiceImpl := service.NewPinNasabahService(pinNasabahRepositoryImpl, db, validate)
	pinNasabahControllerImpl := controller.NewPinNasabahController(pinNasabahServiceImpl)
	router := app.NewRouter(datanasabahControllerImpl, keamananNasabahControllerImpl, akunNasabahControllerImpl, pengajuanKreditControllerImpl, emailValidationControllerImpl, penarikanSaldoControllerImpl, getSaldoControllerImpl, getNikControllerImpl, loginNasabahControllerImpl, getProfileControllerImpl, avaUploadControllerImpl, pinNasabahControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var datanasabahSet = wire.NewSet(repository.NewDatanasabahRepository, wire.Bind(new(repository.DatanasabahRepository), new(*repository.DatanasabahRepositoryImpl)), service.NewDatanasabahService, wire.Bind(new(service.DataNasabahService), new(*service.DatanasabahServiceImpl)), controller.NewDatanasabahController, wire.Bind(new(controller.DatanasabahController), new(*controller.DatanasabahControllerImpl)))

var keamanannasabahSet = wire.NewSet(repository.NewPertanyaanKeamananRepository, wire.Bind(new(repository.KeamananNasabahRepository), new(*repository.PertanyaanKeamananRepositoryImpl)), service.NewKeamananNasabahService, wire.Bind(new(service.KeamananNasabahService), new(*service.KeamananNasabahServiceImpl)), controller.NewKeamananNasabahController, wire.Bind(new(controller.KeamananNasabahController), new(*controller.KeamananNasabahControllerImpl)))

var emailvalidationSet = wire.NewSet(repository.NewEmailValidationRepository, wire.Bind(new(repository.EmailValidationRepository), new(*repository.EmailValidationRepositoryImpl)), service.NewEmailValidationService, wire.Bind(new(service.EmailValidationService), new(*service.EmailValidationServiceImpl)), controller.NewEmailValidationController, wire.Bind(new(controller.EmailValidationController), new(*controller.EmailValidationControllerImpl)))

var pinnasabahSet = wire.NewSet(repository.NewPinNasabahRepositoryImpl, wire.Bind(new(repository.PinNasabahRepository), new(*repository.PinNasabahRepositoryImpl)), service.NewPinNasabahService, wire.Bind(new(service.PinNasabahService), new(*service.PinNasabahServiceImpl)), controller.NewPinNasabahController, wire.Bind(new(controller.PinNasabahController), new(*controller.PinNasabahControllerImpl)))

var pengajuankreditSet = wire.NewSet(repository.NewPengajuanKreditRepository, wire.Bind(new(repository.PengajuanKreditRepository), new(*repository.PengajuanKreditRepositoryImpl)), service.NewPengajuanKreditService, wire.Bind(new(service.PengajuanKreditService), new(*service.PengajuanKreditServiceImpl)), controller.NewPengajuanKreditControllerImpl, wire.Bind(new(controller.PengajuanKreditController), new(*controller.PengajuanKreditControllerImpl)))

var penarikansaldoSet = wire.NewSet(repository.NewPenarikanSaldoRepositoryImpl, wire.Bind(new(repository.PenarikanSaldoRepository), new(*repository.PenarikanSaldoRepositoryImpl)), service.NewPenarikanSaldoServiceImpl, wire.Bind(new(service.PenarikanSaldoService), new(*service.PenarikanSaldoServiceImpl)), controller.NewPenarikanSaldoControllerImpl, wire.Bind(new(controller.PenarikanSaldoController), new(*controller.PenarikanSaldoControllerImpl)))

var akunnasabahSet = wire.NewSet(repository.NewAkunNasabahRepositoryImpl, wire.Bind(new(repository.AkunNasabahRepository), new(*repository.AkunNasabahRepositoryImpl)), service.NewAkunNasabahService, wire.Bind(new(service.AkunNasabahService), new(*service.AkunNasabahServiceImpl)), controller.NewAkunNasabahController, wire.Bind(new(controller.AkunNasabahController), new(*controller.AkunNasabahControllerImpl)))

var getsaldoSet = wire.NewSet(repository.NewGetSaldoRepository, wire.Bind(new(repository.GetSaldoRepository), new(*repository.GetSaldoRepositoryImpl)), service.NewGetSaldoService, wire.Bind(new(service.GetSaldoService), new(*service.GetSaldoServiceImpl)), controller.NewGetSaldoController, wire.Bind(new(controller.GetSaldoController), new(*controller.GetSaldoControllerImpl)))

var getnikSet = wire.NewSet(repository.NewGetNikRepository, wire.Bind(new(repository.GetNikRepository), new(*repository.GetNikRepositoryImpl)), service.NewGetNikService, wire.Bind(new(service.GetNikService), new(*service.GetNikServiceImpl)), controller.NewGetNikController, wire.Bind(new(controller.GetNikController), new(*controller.GetNikControllerImpl)))

var loginSet = wire.NewSet(repository.NewLoginNasabahRepository, wire.Bind(new(repository.LoginNasabahRepository), new(*repository.LoginNasabahRepositoryImpl)), service.NewLoginNasabahService, wire.Bind(new(service.LoginNasabahService), new(*service.LoginNasabahServiceImpl)), controller.NewLoginNasabahController, wire.Bind(new(controller.LoginNasabahController), new(*controller.LoginNasabahControllerImpl)))

var profileSet = wire.NewSet(repository.NewGetProfileRepository, wire.Bind(new(repository.GetProfileRepository), new(*repository.GetProfileRepositoryImpl)), service.NewGetProfileService, wire.Bind(new(service.GetProfileService), new(*service.GetProfileServiceImpl)), controller.NewGetProfileController, wire.Bind(new(controller.GetProfileController), new(*controller.GetProfileControllerImpl)))

var avaSet = wire.NewSet(repository.NewAvaUploadRepository, wire.Bind(new(repository.AvaUploadRepository), new(*repository.AvaUploadRepositoryImpl)), service.NewAvaUploadService, wire.Bind(new(service.AvaUploadService), new(*service.AvaUploadServiceImpl)), controller.NewAvaUploadController, wire.Bind(new(controller.AvaUploadController), new(*controller.AvaUploadControllerImpl)))
